# Generated by Django 5.2.4 on 2025-08-22 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0003_task_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_user',
            new_name='active_user',
        ),
    ]
