# Generated by Django 5.2.5 on 2025-08-24 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0006_alter_task_active_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['id']},
        ),
    ]
